# .github/ISSUE_TEMPLATE/config.yml
# This file is used to configure the issue templates for repository.

blank_issues_enabled: true
contact_links:
  - name: Security Policy
    url: https://github.com/ergiosko/rootine/security/policy
    about: Please report security vulnerabilities here

  - name: Discussions
    url: https://github.com/ergiosko/rootine/discussions
    about: Ask questions and discuss with other community members
