name: Close Stale Issues and PRs

on:
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC every day
  workflow_dispatch:    # Allow manual triggering

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stale:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v9
      with:
        # Token for the repository. Can be passed in using secrets.GITHUB_TOKEN
        repo-token: ${{ secrets.GITHUB_TOKEN }}

        # Settings for stale issues
        days-before-issue-stale: 90
        days-before-issue-close: 7
        stale-issue-message: >
          This issue has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs within 7 days.
          Thank you for your contributions to Rootine!
        close-issue-message: >
          This issue has been automatically closed because it has not had
          recent activity. Feel free to reopen if you believe this is still relevant.

        # Settings for stale PRs
        days-before-pr-stale: 30
        days-before-pr-close: 7
        stale-pr-message: >
          This pull request has been automatically marked as stale because it has not had
          recent activity. It will be closed if no further activity occurs within 7 days.
          Thank you for your contributions to Rootine!
        close-pr-message: >
          This pull request has been automatically closed because it has not had
          recent activity. Feel free to reopen if you'd like to continue working on this.

        # Labels
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'

        # Exempt certain labels from being marked as stale
        exempt-issue-labels: 'pinned,security,bug'
        exempt-pr-labels: 'pinned,security,work-in-progress'

        # Only remove stale label if the issue/PR is updated or commented on
        remove-stale-when-updated: true

        # Limit the number of operations per run to be kinder to the API
        operations-per-run: 100
